### ISSUE TITLE
build 的时候如何指定使用 .env.production的？

### ISSUE THREAD

**Issue by liuyami** [blessleon/nuxt3-ssr-ts#1]
感谢，这个项目了解了更多的NUXT3，但有一个疑问，在 package.json 没看到有响应的代码，build 的时候怎么指定使用 .env.production ？

**Comment by blessleon** [comment]
是的，目前未做指定，需要的话可以在script添加指定`"build:production": "nuxt build --dotenv .env.production"`,  该模板也在逐步完善之中，希望多多提出问题和建议
